# Generated by Django 4.0.7 on 2023-09-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionPlan',
            new_name='Product',
        ),
    ]
